package cli

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"maps"
	"os"
	"os/user"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Austrum-lab/game-fetcher-cli/internal/config"
	"github.com/Austrum-lab/game-fetcher-cli/internal/provider/steam"
	"github.com/Austrum-lab/game-fetcher-cli/internal/state"
)

const generatedMarker = "# Generated by gamefetcher"

func newSystemdGenCmd() *cobra.Command {
	var outDir, runAs, every string
	cmd := &cobra.Command{
		Use:   "systemd-gen [profile|group ...]",
		Short: "Generate systemd units for game servers plus a sync timer",
		Long: `Generates one <profile>.service per profile (the ExecStart is resolved from
Steam's own appinfo launch metadata when present, then by scanning the
install dir, otherwise left as a TODO) and a gamefetcher-sync.service/.timer
pair. Existing files are never overwritten silently: a diff is shown and
confirmation asked; files without the "` + generatedMarker + `" marker get an
extra warning. Units are written to --out; installing them needs root:

  sudo cp *.service *.timer /etc/systemd/system/
  sudo systemctl daemon-reload && sudo systemctl enable --now <unit>`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runSystemdGen(cmd, args, outDir, runAs, every)
		},
	}
	cmd.Flags().StringVarP(&outDir, "out", "o", ".", "directory to write unit files into")
	cmd.Flags().StringVarP(&runAs, "user", "u", "", "User= for the units (default: current user)")
	cmd.Flags().StringVarP(&every, "every", "e", "1h", "sync timer interval (OnUnitActiveSec)")
	return cmd
}

func runSystemdGen(cmd *cobra.Command, args []string, outDir, runAs, every string) error {
	ctx := cmd.Context()
	logf := func(format string, a ...any) { fmt.Fprintf(cmd.ErrOrStderr(), format+"\n", a...) }

	cfg, err := loadConfig(cmd)
	if err != nil {
		return err
	}
	profiles, err := selectProfiles(cfg, args)
	if err != nil {
		return err
	}
	if len(profiles) == 0 {
		return errors.New("no profiles to generate units for")
	}
	path, err := statePath(cfg)
	if err != nil {
		return err
	}
	store, err := state.Open(path)
	if err != nil {
		return err
	}
	if runAs == "" {
		u, err := user.Current()
		if err != nil {
			return err
		}
		runAs = u.Username
	}
	prov := steam.New(steam.Options{
		SteamcmdPath: cfg.SteamcmdPath,
		AllowInstall: cfg.AutoInstallSteamcmd,
		Stdout:       cmd.ErrOrStderr(),
		OutputMode:   outputMode(cmd),
		Progress:     progressOut(cmd),
	})
	infos := map[string]*steam.AppInfo{}
	confirm := askConfirm(cmd)
	errOut := cmd.ErrOrStderr()

	var written []string
	for _, name := range slices.Sorted(maps.Keys(profiles)) {
		p := profiles[name]
		platform := p.Platform
		if platform == "" {
			if cached, ok := store.Platform(strconv.Itoa(p.AppID)); ok && cached != "native" {
				platform = cached
			}
		}
		execStart, notes := resolveExecStart(ctx, prov, infos, p, platform, logf)
		content := renderServiceUnit(name, p, runAs, platform, execStart, notes)
		unitPath := filepath.Join(outDir, name+".service")
		if err := writeGeneratedFile(unitPath, content, confirm, errOut); err != nil {
			return err
		}
		written = append(written, name+".service")
	}

	self, err := os.Executable()
	if err != nil {
		self = "gamefetcher"
	}
	syncSvc := filepath.Join(outDir, "gamefetcher-sync.service")
	if err := writeGeneratedFile(syncSvc, renderSyncService(runAs, self), confirm, errOut); err != nil {
		return err
	}
	syncTimer := filepath.Join(outDir, "gamefetcher-sync.timer")
	if err := writeGeneratedFile(syncTimer, renderSyncTimer(every), confirm, errOut); err != nil {
		return err
	}
	written = append(written, "gamefetcher-sync.service", "gamefetcher-sync.timer")

	fmt.Fprintf(cmd.OutOrStdout(), `
Install (as root):
  sudo cp %s /etc/systemd/system/
  sudo systemctl daemon-reload
  sudo systemctl enable --now gamefetcher-sync.timer
  sudo systemctl enable --now %s
`, strings.Join(written, " "), written[0])
	return nil
}

// resolveExecStart finds what to run, in order of trust: Valve's own
// config.launch entries from appinfo; executables discovered in the install
// dir; an explicit TODO. Windows builds are wrapped in umu-run.
func resolveExecStart(ctx context.Context, prov *steam.Provider, infos map[string]*steam.AppInfo, p config.Profile, platform string, logf func(string, ...any)) (string, []string) {
	target := platform
	if target == "" {
		target = steam.HostOS()
	}
	var notes []string

	if info, err := appInfoMemo(ctx, prov, infos, strconv.Itoa(p.AppID)); err == nil {
		candidates := launchCandidates(info.Launch, target)
		if len(candidates) > 0 {
			chosen := candidates[0]
			execPath := filepath.Join(p.InstallDir, filepath.FromSlash(strings.ReplaceAll(chosen.Executable, `\`, `/`)))
			line := execPath
			if chosen.Arguments != "" {
				line += " " + chosen.Arguments
			}
			notes = append(notes, fmt.Sprintf("# ExecStart from Steam appinfo launch entry (type %q)", chosen.Type))
			for _, alt := range candidates[1:] {
				notes = append(notes, fmt.Sprintf("# alternative launch entry: %s %s", alt.Executable, alt.Arguments))
			}
			return wrapRunner(line, platform), notes
		}
	} else {
		logf("warning: appinfo for %d unavailable (%v); falling back to scanning the install dir", p.AppID, err)
	}

	if found := scanExecutables(p.InstallDir, target); len(found) > 0 {
		notes = append(notes, "# ExecStart guessed from the install dir — appinfo has no launch entry; verify it")
		for _, alt := range found[1:] {
			notes = append(notes, "# other executable found: "+alt)
		}
		return wrapRunner(filepath.Join(p.InstallDir, found[0]), platform), notes
	}

	notes = append(notes,
		"# TODO: Steam appinfo has no launch entry and nothing recognizable was",
		"# found in the install dir — set ExecStart to the server binary manually.")
	return "", notes
}

func launchCandidates(entries []steam.LaunchEntry, target string) []steam.LaunchEntry {
	var matching []steam.LaunchEntry
	for _, e := range entries {
		if len(e.OSes) == 0 || slices.Contains(e.OSes, target) {
			matching = append(matching, e)
		}
	}
	// Server entries first — that's what a dedicated-server unit wants.
	var servers []steam.LaunchEntry
	for _, e := range matching {
		if e.Type == "server" {
			servers = append(servers, e)
		}
	}
	if len(servers) > 0 {
		return servers
	}
	return matching
}

// wrapRunner puts Windows builds behind umu-run (Proton); umu downloads and
// manages Proton itself, it just has to be installed.
func wrapRunner(line, platform string) string {
	if platform == "windows" && steam.HostOS() != "windows" {
		return "umu-run " + line
	}
	return line
}

// scanExecutables lists plausible server entry points at the top level of
// the install dir.
func scanExecutables(dir, target string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		lower := strings.ToLower(name)
		if target == "windows" {
			if strings.HasSuffix(lower, ".exe") || strings.HasSuffix(lower, ".bat") {
				out = append(out, name)
			}
			continue
		}
		if strings.HasSuffix(lower, ".sh") || strings.HasSuffix(lower, ".x86_64") {
			out = append(out, name)
			continue
		}
		if info, err := e.Info(); err == nil && info.Mode()&0o111 != 0 {
			out = append(out, name)
		}
	}
	slices.Sort(out)
	return out
}

func renderServiceUnit(name string, p config.Profile, runAs, platform, execStart string, notes []string) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n")
	for _, n := range notes {
		b.WriteString(n + "\n")
	}
	fmt.Fprintf(&b, `[Unit]
Description=%s (Steam app %d)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=%s
WorkingDirectory=%s
`, name, p.AppID, runAs, p.InstallDir)
	if execStart != "" {
		fmt.Fprintf(&b, "ExecStart=%s\n", execStart)
	} else {
		b.WriteString("# ExecStart=<path to the server binary>\n")
	}
	if platform == "windows" && steam.HostOS() != "windows" {
		b.WriteString("# umu-run manages Proton automatically; install it once (e.g. pipx install umu-launcher)\n")
		b.WriteString("Environment=GAMEID=0\n")
	}
	b.WriteString(`Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
`)
	return b.String()
}

func renderSyncService(runAs, self string) string {
	return fmt.Sprintf(`%s
[Unit]
Description=gamefetcher sync
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
User=%s
ExecStart=%s sync
`, generatedMarker, runAs, self)
}

func renderSyncTimer(every string) string {
	return fmt.Sprintf(`%s
[Unit]
Description=periodic gamefetcher sync

[Timer]
OnBootSec=5min
OnUnitActiveSec=%s
Persistent=true

[Install]
WantedBy=timers.target
`, generatedMarker, every)
}

// writeGeneratedFile writes content to path; an existing file is never
// replaced silently — identical content is a no-op, anything else shows a
// diff and asks, with an extra warning when the file was not generated by
// this tool.
func writeGeneratedFile(path, content string, confirm func(string) (bool, error), out io.Writer) error {
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		if bytes.Equal(existing, []byte(content)) {
			fmt.Fprintf(out, "%s is up to date\n", path)
			return nil
		}
		fmt.Fprintf(out, "%s already exists:\n%s", path, diffLines(existing, []byte(content)))
		prompt := fmt.Sprintf("Overwrite %s?", path)
		if !bytes.Contains(existing, []byte(generatedMarker)) {
			prompt = fmt.Sprintf("Overwrite %s? (the existing file was NOT generated by gamefetcher)", path)
		}
		ok, err := confirm(prompt)
		if err != nil {
			return err
		}
		if !ok {
			return fmt.Errorf("aborted, %s left untouched", path)
		}
	case !errors.Is(err, fs.ErrNotExist):
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(out, "wrote %s\n", path)
	return nil
}
