package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The test config has no reachable steamcmd, so ExecStart resolution falls
// through appinfo to the install-dir scan and the TODO placeholder.
func TestSystemdGenFallbacks(t *testing.T) {
	dir := t.TempDir()
	installDir := filepath.Join(dir, "srv")
	if err := os.MkdirAll(installDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(installDir, "run_server.sh"), []byte("#!/bin/sh\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	cfgPath := filepath.Join(dir, "gamefetcher.yaml")
	content := "state_path: " + filepath.Join(dir, "state.json") + "\n" +
		"steamcmd_path: " + filepath.Join(dir, "no-such-steamcmd") + "\n" +
		"profiles:\n" +
		"  scanned:\n    app_id: 111\n    install_dir: " + installDir + "\n" +
		"  empty:\n    app_id: 222\n    install_dir: " + filepath.Join(dir, "nothing") + "\n"
	if err := os.WriteFile(cfgPath, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	outDir := filepath.Join(dir, "units")
	os.MkdirAll(outDir, 0o755)

	out, err := execRoot(t, "--config", cfgPath, "systemd-gen", "--out", outDir, "--user", "gamefetcher")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "sudo cp") {
		t.Errorf("install instructions missing:\n%s", out)
	}

	scanned, err := os.ReadFile(filepath.Join(outDir, "scanned.service"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		generatedMarker,
		"User=gamefetcher",
		"WorkingDirectory=" + installDir,
		"ExecStart=" + filepath.Join(installDir, "run_server.sh"),
		"WantedBy=multi-user.target",
	} {
		if !strings.Contains(string(scanned), want) {
			t.Errorf("scanned.service lacks %q:\n%s", want, scanned)
		}
	}

	empty, err := os.ReadFile(filepath.Join(outDir, "empty.service"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(empty), "TODO") || strings.Contains(string(empty), "\nExecStart=") {
		t.Errorf("empty.service must carry a TODO and no active ExecStart:\n%s", empty)
	}

	for _, f := range []string{"gamefetcher-sync.service", "gamefetcher-sync.timer"} {
		raw, err := os.ReadFile(filepath.Join(outDir, f))
		if err != nil {
			t.Fatalf("%s not written: %v", f, err)
		}
		if !strings.Contains(string(raw), generatedMarker) {
			t.Errorf("%s lacks the marker", f)
		}
	}
}

func TestWriteGeneratedFileProtection(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.service")
	var out strings.Builder

	// New file: written without questions.
	if err := writeGeneratedFile(path, generatedMarker+"\nA\n", confirmBoom, &out); err != nil {
		t.Fatal(err)
	}
	// Identical: no-op, no confirmation.
	if err := writeGeneratedFile(path, generatedMarker+"\nA\n", confirmBoom, &out); err != nil {
		t.Fatal(err)
	}
	// Changed + declined: error, file intact.
	if err := writeGeneratedFile(path, generatedMarker+"\nB\n", confirmNo, &out); err == nil {
		t.Fatal("declined overwrite must fail")
	}
	if raw, _ := os.ReadFile(path); !strings.Contains(string(raw), "A") {
		t.Fatal("declined overwrite still changed the file")
	}

	// Foreign file (no marker): the prompt must warn about it.
	foreign := filepath.Join(dir, "foreign.service")
	os.WriteFile(foreign, []byte("[Unit]\nDescription=someone else's\n"), 0o644)
	var prompt string
	capture := func(p string) (bool, error) { prompt = p; return true, nil }
	if err := writeGeneratedFile(foreign, generatedMarker+"\nnew\n", capture, &out); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(prompt, "NOT generated by gamefetcher") {
		t.Errorf("foreign-file warning missing from prompt: %q", prompt)
	}
}

func TestStatusJSON(t *testing.T) {
	out, err := execRoot(t, "--config", testConfig(t), "status", "--json")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, `"profile": "sdk"`) || !strings.Contains(out, `"installed": false`) {
		t.Fatalf("status json unexpected:\n%s", out)
	}
}
